# Generated by Django 5.1.6 on 2025-02-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='categories',
        ),
    ]
