# Generated by Django 5.1.6 on 2025-02-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
